---
title: "Simulations"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Let's simulate something.

I have a function 


```{r}
sim_mean_sd = function(sample_size, mu = 3, sigma = 4) {
  
  sim_data = 
    tibble(
    x = rnorm(n = sample_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarise(
    mean = mean(x),
    sd = sd(x)
  )

}
```

I can "simulate" by running this line

```{r}
sim_mean_sd(30)
```


## Let's simulate a lot

Let's atart with a for loop.

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(sample_size = 30)
  
}

bind_rows(output)
```

Let's use a loop function

```{r}
sim_results = 
  rerun(100, sim_mean_sd(sample_size = 30)) %>% 
  bind_rows()
```

Let's look at results...

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) + geom_density()

sim_results %>% 
  summarise(
    avg_sample_mean = mean(mean),
    sd_sample_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) + geom_density()
```

## Let's try other sample sizes. 

```{r}
n_list = 
  list(
    "n = 30" = 30,
    "n = 60" = 60,
    "n = 120" = 120,
    "n = 240" = 240
  )

output = vector("list", length = 4)

output[[1]] = rerun(100, sim_mean_sd(sample_size = n_list[[1]])) %>% bind_rows()
output[[2]] = rerun(100, sim_mean_sd(sample_size = n_list[[2]])) %>% bind_rows()

for (i in 1:4) {
  
  output[[i]] = 
    rerun(100, sim_mean_sd(sample_size = n_list[[i]])) %>% 
    bind_rows()
  
}
```


```{r}
sim_results = 
  tibble(
  sample_size = c(30, 60, 120, 240)
) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~ rerun(1000, sim_mean_sd(.x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)
```

Do zome data frame things. 

```{r}
sim_results %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mean)) +
  geom_violin()
```

```{r}
sim_results %>% 
  group_by(sample_size) %>% 
  summarise(
    avg_sample_mean = mean(mean),
    sd_sample_mean = sd(mean)
  )
```

`set.seed(1)` is the function that used to keep the same random numbers





